# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-06 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumb',
            field=models.ImageField(blank=True, default=b'default.png', upload_to=b''),
        ),
    ]
