# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-20 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_thumb'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('filepath', models.FileField(null=True, upload_to=b'files/', verbose_name=b'')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='thumb',
        ),
    ]
